version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    desc: Install dependencies
    cmds:
      - pnpm install
      - pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build

  dev:
    deps: [ install ]
    cmds:
      - pnpm run dev

  publish-to-npmjs:
    desc: Publish package to npmjs.
    cmds:
      - pnpm publish
